apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName}}
type: Opaque
data:
  username: {{ .Values.database.userName | required "database username is required" | b64enc | quote }}
  password: {{.Values.database.password | required "database password is required" | b64enc | quote }}